-- Esquema compatible con H2 (modo PostgreSQL) y PostgreSQL 14+

CREATE TABLE usuario (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(50)  NOT NULL UNIQUE,
    password_hash   VARCHAR(100) NOT NULL,
    nombre          VARCHAR(120) NOT NULL,
    rol             VARCHAR(20)  NOT NULL,
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    creado_en       TIMESTAMP    NOT NULL
);

CREATE TABLE cliente (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curp              VARCHAR(18)  NOT NULL UNIQUE,
    rfc               VARCHAR(13),
    nombre            VARCHAR(80)  NOT NULL,
    apellido_paterno  VARCHAR(80)  NOT NULL,
    apellido_materno  VARCHAR(80),
    fecha_nacimiento  DATE         NOT NULL,
    email             VARCHAR(120) NOT NULL UNIQUE,
    telefono          VARCHAR(15),
    estado_kyc        VARCHAR(20)  NOT NULL,
    creado_en         TIMESTAMP    NOT NULL,
    actualizado_en    TIMESTAMP    NOT NULL,
    version           BIGINT       NOT NULL DEFAULT 0
);

CREATE TABLE verificacion_biometrica (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id           BIGINT        NOT NULL REFERENCES cliente (id),
    puntaje              NUMERIC(5, 4) NOT NULL,
    umbral               NUMERIC(5, 4) NOT NULL,
    aprobada             BOOLEAN       NOT NULL,
    huella_identificacion VARCHAR(64)  NOT NULL,
    huella_selfie        VARCHAR(64)   NOT NULL,
    realizada_por        VARCHAR(50)   NOT NULL,
    creado_en            TIMESTAMP     NOT NULL
);
CREATE INDEX idx_verif_cliente ON verificacion_biometrica (cliente_id);

CREATE TABLE cuenta (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clabe       VARCHAR(18)    NOT NULL UNIQUE,
    cliente_id  BIGINT         NOT NULL REFERENCES cliente (id),
    saldo       NUMERIC(19, 2) NOT NULL DEFAULT 0,
    moneda      VARCHAR(3)     NOT NULL DEFAULT 'MXN',
    estado      VARCHAR(20)    NOT NULL,
    creado_en   TIMESTAMP      NOT NULL,
    version     BIGINT         NOT NULL DEFAULT 0,
    CONSTRAINT chk_saldo_no_negativo CHECK (saldo >= 0)
);
CREATE INDEX idx_cuenta_cliente ON cuenta (cliente_id);

CREATE TABLE transaccion (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folio               VARCHAR(36)    NOT NULL UNIQUE,
    tipo                VARCHAR(20)    NOT NULL,
    cuenta_origen_id    BIGINT REFERENCES cuenta (id),
    cuenta_destino_id   BIGINT REFERENCES cuenta (id),
    monto               NUMERIC(19, 2) NOT NULL,
    concepto            VARCHAR(140),
    estado              VARCHAR(20)    NOT NULL,
    clave_idempotencia  VARCHAR(64)    UNIQUE,
    realizada_por       VARCHAR(50)    NOT NULL,
    creado_en           TIMESTAMP      NOT NULL,
    CONSTRAINT chk_monto_positivo CHECK (monto > 0)
);
CREATE INDEX idx_tx_origen ON transaccion (cuenta_origen_id);
CREATE INDEX idx_tx_destino ON transaccion (cuenta_destino_id);
CREATE INDEX idx_tx_fecha ON transaccion (creado_en);

CREATE TABLE evento_auditoria (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario     VARCHAR(50)  NOT NULL,
    accion      VARCHAR(40)  NOT NULL,
    entidad     VARCHAR(40)  NOT NULL,
    entidad_id  VARCHAR(40),
    detalle     VARCHAR(500),
    creado_en   TIMESTAMP    NOT NULL
);
CREATE INDEX idx_auditoria_fecha ON evento_auditoria (creado_en);
